### PR TITLE
add Insecure to RestoreOperationRequest

### LINKED ISSUE #3: [BUG] Insecure parameter missing in restore Request?
**Describe the bug**
The [backup operation request](https://github.com/instaclustr/instaclustr-icarus-go-client/blob/master/pkg/instaclustr_icarus/model_backup_operation_request.go#L41) contains the field `Insecure`. This field is missing in the [restore operation request](https://github.com/instaclustr/instaclustr-icarus-go-client/blob/master/pkg/instaclustr_icarus/model_restore_operation_request.go). I imagine it's needed there as well?

**Versions (please complete the following information):**
 - 1.0.5 (current)

### PR DESCRIPTION
**Pull request by an-tex**
(and implicitly to RestoreOperationResponse)

I tried running `./regenerate.sh`, it worked fine with regenerating the Insecure part in the `model_restore_operation*.go` and `RestoreOperation*.md` files but I also got a lot of other changes in other files e.g. 
```
Progress float64 `json:"progress"`
```
to
```
Progress string `json:"progress"`
```

and new 
```
import (
	"time"
)
```

fixes https://github.com/instaclustr/instaclustr-icarus-go-client/issues/3

### CODE REVIEW

**Comment by smiklosovic** [comment]
Yes, the regeneration does change some stuff in such a way that is incompatible with how we want to use it ... Automatic generation is not so automatic after all for us so we need to tweak some things manually and regeneration will change it back so we have to revert it how we want it to be.

Thanks, merging.

**Comment by an-tex** [comment]
Hi @smiklosovic ,
do you plan to publish a new release to [pkg.go.dev](https://pkg.go.dev/github.com/instaclustr/instaclustr-icarus-go-client@v0.0.0-20210121184104-1f9f5e201fe2/pkg/instaclustr_icarus?tab=versions) any time soon? Would love to get things going on the [casskop](https://github.com/Orange-OpenSource/casskop/issues/310) side of things :)
Cheers

**Comment by smiklosovic** [comment]
hey @an-tex 

I am looking at that website for the very first time, how does this work? We have never published there anything on our own (from Instaclustr).

Maybe @cscetbon knows more?

**Comment by an-tex** [comment]
> I am looking at that website for the very first time, how does this work? We have never published there anything on our own (from Instaclustr).

No idea either, I just know it's used in [casskop as a dependency](https://github.com/Orange-OpenSource/casskop/blob/master/go.mod#L15)

Edit: There's doc about [adding a package](https://go.dev/about#adding-a-package), even though I don't see that mentioned "request" button.

**Pull request merged**
